version: "2"

services:
    frontend:
        build: ./frontend
        command: "npm start"
        ports:
            - "3000:3000"
    backend:
        build: ./backend
        command: "npm start"
        ports:
            - "3001:3001"
